// Training/Angular_React_Vue/Day3/Assignments/Angular/Source/LoginProject/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  name="";
  address="";
  panNumber="";

  output="";
  signup()
  {
    this.output = `Name: ${this.name}, Address: ${this.address}, PAN Number: ${this.panNumber}`;
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container">
    <div class="row">
        <div class="col text-center bg-primary">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-4 mx-auto">
            <input type="text" class="form-control" placeholder="Enter Name Here." [(ngModel)]="name"> <br>
            <textarea class="form-control" placeholder="Enter Address Here." [(ngModel)]="address"></textarea><br>
            <input type="text" class="form-control" placeholder="Enter PAN Number Here." [(ngModel)]="panNumber"> <br>

            <button class="btn btn-warning" (click)="signup()">Sign Up</button>
            <br>
            <p>{{output}}</p>
        </div>
    </div>
</div>

// Training/Angular_React_Vue/Day3/Assignments/Vue/Source/loginproject/src/components/Signup.vue
<template>
  <div class="text-center">
    <h1 class="text-center bg-danger text-white">Sign Up</h1><hr>

    <div class="container">
        <div class="row">
            <div class="col-6 mx-auto text-center">
                <table class="text-center">
                  <caption hidden>Table</caption>
                    <tr>
                        <th scope="labels"><h3>Enter Name:</h3></th>
                        <td><input type="text" placeholder="Please Enter Name" v-model="name"/></td>
                    </tr>
                    <tr>
                        <th scope="labels"><h3>Enter Address :</h3></th>
                        <td><input type="text" placeholder="Please Enter Address" v-model="address"/></td>
                    </tr>
                    <tr>
                        <th scope="labels"><h3>Enter PAN Number:</h3></th>
                        <td><input type="text" placeholder="Please Enter Pan-number" v-model="pan"/></td>
                    </tr>
                    <tr>
                        <td colspan="2"><button class="btn btn-info" @click="signup">Sign Up</button></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <p>{{result}}</p>
  </div>
</template>

<script>
export default {
  name: 'SignupPage',
  data(){
    return{
      name : '',
      address : '',
      pan : '',
      result : '',
    }
  },

  methods:{
    signup(){
          if(this.name !="" && this.address!=" " && this.pan!=""){
            this.display();
            alert("Sign up Successfully completed!!!")
          }
          else{
            alert("Please fill all fields..")
          }
        },

        display(){
            this.result = `Name : ${this.name}, Address : ${this.address}, Pan-Number : ${this.pan}`
        }
    }
}
</script>
