// Training/Angular_React_Vue/Day11/Assignments/Angular/ResumeProject/Source/ResumeProject/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ResumeProject';
}

<div class="container-fluid">
  <div class="row bg-primary">
    <div class="col text-white text-center">
      <h1>Resume</h1>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-3 py-3 bg-dark d-flex flex-column justify-content-around">
      <img class="img-fluid rounded-circle border border-5 border-white my-4" src="../assets/mypic.jpg" alt="img">
      <button class="btn btn-primary text-white my-2 fw-bold text-center" routerLink="/about">About</button>
      <button class="btn btn-primary text-white my-2 fw-bold text-center" routerLink="/education">Education</button>
      <button class="btn btn-primary text-white my-2 fw-bold text-center" routerLink="/technical-skills">Technical Skills</button>
      <button class="btn btn-primary text-white my-2 fw-bold text-center" routerLink="projects">Projects</button>
    </div>
    <div class="col-9">
      <router-outlet></router-outlet>
    </div>
  </div>
</div>

// Training/Angular_React_Vue/Day14/Assignments/React/Source/indexproject/src/App.js
import {Link,Outlet } from 'react-router-dom';
import './App.css';

function App() {
  return (
    <div className="App">
      <div className="container-fluid">
        <div className="row">
          <div className="p-2 bg-dark col d-flex justify-content-evenly">
            <Link to="/html" className='btn btn-warning'>HTML</Link>
            <Link to="/css" className='btn btn-warning'>CSS</Link>
            <Link to="/js" className='btn btn-warning'>JavaScript</Link>
          </div>
        </div>
        <div className='row'>
          <Outlet></Outlet>
        </div>
      </div>
    </div>
  );
}

export default App;
