// Training/Angular/Day7/Practice/Source/ChildToParent/src/app/profile/profile.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';


@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {

  @Output() dataEvent = new EventEmitter<any>();

  
  username='';

  constructor() { }

  ngOnInit(): void {
  }

  sendData()
  {
    this.dataEvent.emit(this.username);
  }

}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="text-center bg-warning">Profile</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-4 mx-auto">
            <input type="text" placeholder="Name here" class="form-control" [(ngModel)]="username">
            <p>{{username}}</p>

            <button class="btn btn-warning" (click)="sendData()">Send</button>
        </div>
    </div>
</div>

// Training/Angular_React_Vue/Day7/Practice/Vue/ChildToParent/Source/childtoparent/src/components/Profile.vue
<template>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="text-center bg-warning">Profile</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-4 mx-auto">
            <input type="text" placeholder="Name here" class="form-control" v-model="username">
            <p>{{username}}</p>

            <button class="btn btn-warning" @click="sendData()">Send</button>
        </div>
    </div>
</div>
</template>

<script>
export default {
    name:"ProfileComponent",
    data()
    {
        return{
            username:""
        }
    },
    methods:
    {
        sendData()
        {
            this.$emit("getData",this.username);
        }
    }
}
</script>
