// Training/Angular_React_Vue/Day14/Assignments/React/Source/indexproject/src/App.js
import {Link,Outlet } from 'react-router-dom';
import './App.css';

function App() {
  return (
    <div className="App">
      <div className="container-fluid">
        <div className="row">
          <div className="p-2 bg-dark col d-flex justify-content-evenly">
            <Link to="/html" className='btn btn-warning'>HTML</Link>
            <Link to="/css" className='btn btn-warning'>CSS</Link>
            <Link to="/js" className='btn btn-warning'>JavaScript</Link>
          </div>
        </div>
        <div className='row'>
          <Outlet></Outlet>
        </div>
      </div>
    </div>
  );
}

export default App;

// Training/Angular/Day12/Assignments/UserListProject/Source/UserListProject/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'UserListProject';

  userList:Array<any>=[{"userID":1,"userName":"Roy"},{"userID":2,"userName":"Rohit"}]
}

<div class="container">
  <div class="row" *ngFor="let obj of userList" >
    <div class="col-2"><button class="btn btn-warning" [routerLink]="['/user-list',obj.userID]">{{obj.userName}}</button></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <router-outlet></router-outlet>
    </div>
  </div>
</div>
